// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ProductImage_ProductImageType int32

const (
	ProductImage_PRODUCT_IMAGE_TYPE_UNKNOWN ProductImage_ProductImageType = 0
)

var ProductImage_ProductImageType_name = map[int32]string{
	0: "PRODUCT_IMAGE_TYPE_UNKNOWN",
}

var ProductImage_ProductImageType_value = map[string]int32{
	"PRODUCT_IMAGE_TYPE_UNKNOWN": 0,
}

func (x ProductImage_ProductImageType) String() string {
	return proto.EnumName(ProductImage_ProductImageType_name, int32(x))
}

func (ProductImage_ProductImageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{3, 0}
}

type ProductLink_ProductLinkType int32

const (
	ProductLink_PRODUCT_LINK_TYPE_UNKNOWN ProductLink_ProductLinkType = 0
)

var ProductLink_ProductLinkType_name = map[int32]string{
	0: "PRODUCT_LINK_TYPE_UNKNOWN",
}

var ProductLink_ProductLinkType_value = map[string]int32{
	"PRODUCT_LINK_TYPE_UNKNOWN": 0,
}

func (x ProductLink_ProductLinkType) String() string {
	return proto.EnumName(ProductLink_ProductLinkType_name, int32(x))
}

func (ProductLink_ProductLinkType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{4, 0}
}

type User struct {
	Id                   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamps           *Timestamps `protobuf:"bytes,2,opt,name=timestamps,proto3" json:"timestamps,omitempty"`
	Name                 string      `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetTimestamps() *Timestamps {
	if m != nil {
		return m.Timestamps
	}
	return nil
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ReviewLike struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Review               *Review  `protobuf:"bytes,2,opt,name=review,proto3" json:"review,omitempty"`
	User                 *User    `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReviewLike) Reset()         { *m = ReviewLike{} }
func (m *ReviewLike) String() string { return proto.CompactTextString(m) }
func (*ReviewLike) ProtoMessage()    {}
func (*ReviewLike) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{1}
}

func (m *ReviewLike) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReviewLike.Unmarshal(m, b)
}
func (m *ReviewLike) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReviewLike.Marshal(b, m, deterministic)
}
func (m *ReviewLike) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReviewLike.Merge(m, src)
}
func (m *ReviewLike) XXX_Size() int {
	return xxx_messageInfo_ReviewLike.Size(m)
}
func (m *ReviewLike) XXX_DiscardUnknown() {
	xxx_messageInfo_ReviewLike.DiscardUnknown(m)
}

var xxx_messageInfo_ReviewLike proto.InternalMessageInfo

func (m *ReviewLike) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ReviewLike) GetReview() *Review {
	if m != nil {
		return m.Review
	}
	return nil
}

func (m *ReviewLike) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type Review struct {
	Id                   string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamps           *Timestamps   `protobuf:"bytes,2,opt,name=timestamps,proto3" json:"timestamps,omitempty"`
	Product              *Product      `protobuf:"bytes,3,opt,name=product,proto3" json:"product,omitempty"`
	User                 *User         `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	Content              string        `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Likes                []*ReviewLike `protobuf:"bytes,6,rep,name=likes,proto3" json:"likes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Review) Reset()         { *m = Review{} }
func (m *Review) String() string { return proto.CompactTextString(m) }
func (*Review) ProtoMessage()    {}
func (*Review) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{2}
}

func (m *Review) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Review.Unmarshal(m, b)
}
func (m *Review) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Review.Marshal(b, m, deterministic)
}
func (m *Review) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Review.Merge(m, src)
}
func (m *Review) XXX_Size() int {
	return xxx_messageInfo_Review.Size(m)
}
func (m *Review) XXX_DiscardUnknown() {
	xxx_messageInfo_Review.DiscardUnknown(m)
}

var xxx_messageInfo_Review proto.InternalMessageInfo

func (m *Review) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Review) GetTimestamps() *Timestamps {
	if m != nil {
		return m.Timestamps
	}
	return nil
}

func (m *Review) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

func (m *Review) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Review) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Review) GetLikes() []*ReviewLike {
	if m != nil {
		return m.Likes
	}
	return nil
}

type ProductImage struct {
	Id                   string                        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 ProductImage_ProductImageType `protobuf:"varint,2,opt,name=type,proto3,enum=protos.ProductImage_ProductImageType" json:"type,omitempty"`
	Url                  string                        `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *ProductImage) Reset()         { *m = ProductImage{} }
func (m *ProductImage) String() string { return proto.CompactTextString(m) }
func (*ProductImage) ProtoMessage()    {}
func (*ProductImage) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{3}
}

func (m *ProductImage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductImage.Unmarshal(m, b)
}
func (m *ProductImage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductImage.Marshal(b, m, deterministic)
}
func (m *ProductImage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductImage.Merge(m, src)
}
func (m *ProductImage) XXX_Size() int {
	return xxx_messageInfo_ProductImage.Size(m)
}
func (m *ProductImage) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductImage.DiscardUnknown(m)
}

var xxx_messageInfo_ProductImage proto.InternalMessageInfo

func (m *ProductImage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ProductImage) GetType() ProductImage_ProductImageType {
	if m != nil {
		return m.Type
	}
	return ProductImage_PRODUCT_IMAGE_TYPE_UNKNOWN
}

func (m *ProductImage) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type ProductLink struct {
	Id                   string                      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 ProductLink_ProductLinkType `protobuf:"varint,2,opt,name=type,proto3,enum=protos.ProductLink_ProductLinkType" json:"type,omitempty"`
	Url                  string                      `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *ProductLink) Reset()         { *m = ProductLink{} }
func (m *ProductLink) String() string { return proto.CompactTextString(m) }
func (*ProductLink) ProtoMessage()    {}
func (*ProductLink) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{4}
}

func (m *ProductLink) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductLink.Unmarshal(m, b)
}
func (m *ProductLink) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductLink.Marshal(b, m, deterministic)
}
func (m *ProductLink) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductLink.Merge(m, src)
}
func (m *ProductLink) XXX_Size() int {
	return xxx_messageInfo_ProductLink.Size(m)
}
func (m *ProductLink) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductLink.DiscardUnknown(m)
}

var xxx_messageInfo_ProductLink proto.InternalMessageInfo

func (m *ProductLink) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ProductLink) GetType() ProductLink_ProductLinkType {
	if m != nil {
		return m.Type
	}
	return ProductLink_PRODUCT_LINK_TYPE_UNKNOWN
}

func (m *ProductLink) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type Product struct {
	Id                   string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamps           *Timestamps     `protobuf:"bytes,2,opt,name=timestamps,proto3" json:"timestamps,omitempty"`
	Title                string          `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description          string          `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Images               []*ProductImage `protobuf:"bytes,5,rep,name=images,proto3" json:"images,omitempty"`
	Links                []*ProductLink  `protobuf:"bytes,6,rep,name=links,proto3" json:"links,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{5}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product) GetTimestamps() *Timestamps {
	if m != nil {
		return m.Timestamps
	}
	return nil
}

func (m *Product) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Product) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Product) GetImages() []*ProductImage {
	if m != nil {
		return m.Images
	}
	return nil
}

func (m *Product) GetLinks() []*ProductLink {
	if m != nil {
		return m.Links
	}
	return nil
}

type Timestamps struct {
	Created              *timestamp.Timestamp `protobuf:"bytes,4,opt,name=created,proto3" json:"created,omitempty"`
	Updated              *timestamp.Timestamp `protobuf:"bytes,5,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Timestamps) Reset()         { *m = Timestamps{} }
func (m *Timestamps) String() string { return proto.CompactTextString(m) }
func (*Timestamps) ProtoMessage()    {}
func (*Timestamps) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{6}
}

func (m *Timestamps) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Timestamps.Unmarshal(m, b)
}
func (m *Timestamps) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Timestamps.Marshal(b, m, deterministic)
}
func (m *Timestamps) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Timestamps.Merge(m, src)
}
func (m *Timestamps) XXX_Size() int {
	return xxx_messageInfo_Timestamps.Size(m)
}
func (m *Timestamps) XXX_DiscardUnknown() {
	xxx_messageInfo_Timestamps.DiscardUnknown(m)
}

var xxx_messageInfo_Timestamps proto.InternalMessageInfo

func (m *Timestamps) GetCreated() *timestamp.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *Timestamps) GetUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.Updated
	}
	return nil
}

type GetUserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{7}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type GetUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{8}
}

func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type CreateUserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{9}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type CreateUserResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{10}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

type UpdateUserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{11}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateUserResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserResponse) Reset()         { *m = UpdateUserResponse{} }
func (m *UpdateUserResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserResponse) ProtoMessage()    {}
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{12}
}

func (m *UpdateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserResponse.Unmarshal(m, b)
}
func (m *UpdateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserResponse.Merge(m, src)
}
func (m *UpdateUserResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserResponse.Size(m)
}
func (m *UpdateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserResponse proto.InternalMessageInfo

type DeleteUserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{13}
}

func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(m, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

func (m *DeleteUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type DeleteUserResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserResponse) Reset()         { *m = DeleteUserResponse{} }
func (m *DeleteUserResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteUserResponse) ProtoMessage()    {}
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{14}
}

func (m *DeleteUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserResponse.Unmarshal(m, b)
}
func (m *DeleteUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserResponse.Marshal(b, m, deterministic)
}
func (m *DeleteUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserResponse.Merge(m, src)
}
func (m *DeleteUserResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteUserResponse.Size(m)
}
func (m *DeleteUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserResponse proto.InternalMessageInfo

type ListUsersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsersRequest) Reset()         { *m = ListUsersRequest{} }
func (m *ListUsersRequest) String() string { return proto.CompactTextString(m) }
func (*ListUsersRequest) ProtoMessage()    {}
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{15}
}

func (m *ListUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersRequest.Unmarshal(m, b)
}
func (m *ListUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersRequest.Marshal(b, m, deterministic)
}
func (m *ListUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersRequest.Merge(m, src)
}
func (m *ListUsersRequest) XXX_Size() int {
	return xxx_messageInfo_ListUsersRequest.Size(m)
}
func (m *ListUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersRequest proto.InternalMessageInfo

type ListUsersResponse struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsersResponse) Reset()         { *m = ListUsersResponse{} }
func (m *ListUsersResponse) String() string { return proto.CompactTextString(m) }
func (*ListUsersResponse) ProtoMessage()    {}
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{16}
}

func (m *ListUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersResponse.Unmarshal(m, b)
}
func (m *ListUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersResponse.Marshal(b, m, deterministic)
}
func (m *ListUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersResponse.Merge(m, src)
}
func (m *ListUsersResponse) XXX_Size() int {
	return xxx_messageInfo_ListUsersResponse.Size(m)
}
func (m *ListUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersResponse proto.InternalMessageInfo

func (m *ListUsersResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type GetReviewRequest struct {
	Review               *Review  `protobuf:"bytes,1,opt,name=review,proto3" json:"review,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReviewRequest) Reset()         { *m = GetReviewRequest{} }
func (m *GetReviewRequest) String() string { return proto.CompactTextString(m) }
func (*GetReviewRequest) ProtoMessage()    {}
func (*GetReviewRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{17}
}

func (m *GetReviewRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReviewRequest.Unmarshal(m, b)
}
func (m *GetReviewRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReviewRequest.Marshal(b, m, deterministic)
}
func (m *GetReviewRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReviewRequest.Merge(m, src)
}
func (m *GetReviewRequest) XXX_Size() int {
	return xxx_messageInfo_GetReviewRequest.Size(m)
}
func (m *GetReviewRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReviewRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetReviewRequest proto.InternalMessageInfo

func (m *GetReviewRequest) GetReview() *Review {
	if m != nil {
		return m.Review
	}
	return nil
}

type GetReviewResponse struct {
	Review               *Review  `protobuf:"bytes,1,opt,name=review,proto3" json:"review,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReviewResponse) Reset()         { *m = GetReviewResponse{} }
func (m *GetReviewResponse) String() string { return proto.CompactTextString(m) }
func (*GetReviewResponse) ProtoMessage()    {}
func (*GetReviewResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{18}
}

func (m *GetReviewResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReviewResponse.Unmarshal(m, b)
}
func (m *GetReviewResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReviewResponse.Marshal(b, m, deterministic)
}
func (m *GetReviewResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReviewResponse.Merge(m, src)
}
func (m *GetReviewResponse) XXX_Size() int {
	return xxx_messageInfo_GetReviewResponse.Size(m)
}
func (m *GetReviewResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReviewResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetReviewResponse proto.InternalMessageInfo

func (m *GetReviewResponse) GetReview() *Review {
	if m != nil {
		return m.Review
	}
	return nil
}

type CreateReviewRequest struct {
	Review               *Review  `protobuf:"bytes,1,opt,name=review,proto3" json:"review,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateReviewRequest) Reset()         { *m = CreateReviewRequest{} }
func (m *CreateReviewRequest) String() string { return proto.CompactTextString(m) }
func (*CreateReviewRequest) ProtoMessage()    {}
func (*CreateReviewRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{19}
}

func (m *CreateReviewRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReviewRequest.Unmarshal(m, b)
}
func (m *CreateReviewRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReviewRequest.Marshal(b, m, deterministic)
}
func (m *CreateReviewRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReviewRequest.Merge(m, src)
}
func (m *CreateReviewRequest) XXX_Size() int {
	return xxx_messageInfo_CreateReviewRequest.Size(m)
}
func (m *CreateReviewRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReviewRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReviewRequest proto.InternalMessageInfo

func (m *CreateReviewRequest) GetReview() *Review {
	if m != nil {
		return m.Review
	}
	return nil
}

type CreateReviewResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateReviewResponse) Reset()         { *m = CreateReviewResponse{} }
func (m *CreateReviewResponse) String() string { return proto.CompactTextString(m) }
func (*CreateReviewResponse) ProtoMessage()    {}
func (*CreateReviewResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{20}
}

func (m *CreateReviewResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReviewResponse.Unmarshal(m, b)
}
func (m *CreateReviewResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReviewResponse.Marshal(b, m, deterministic)
}
func (m *CreateReviewResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReviewResponse.Merge(m, src)
}
func (m *CreateReviewResponse) XXX_Size() int {
	return xxx_messageInfo_CreateReviewResponse.Size(m)
}
func (m *CreateReviewResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReviewResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReviewResponse proto.InternalMessageInfo

type DeleteReviewRequest struct {
	Review               *Review  `protobuf:"bytes,1,opt,name=review,proto3" json:"review,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteReviewRequest) Reset()         { *m = DeleteReviewRequest{} }
func (m *DeleteReviewRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteReviewRequest) ProtoMessage()    {}
func (*DeleteReviewRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{21}
}

func (m *DeleteReviewRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteReviewRequest.Unmarshal(m, b)
}
func (m *DeleteReviewRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteReviewRequest.Marshal(b, m, deterministic)
}
func (m *DeleteReviewRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteReviewRequest.Merge(m, src)
}
func (m *DeleteReviewRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteReviewRequest.Size(m)
}
func (m *DeleteReviewRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteReviewRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteReviewRequest proto.InternalMessageInfo

func (m *DeleteReviewRequest) GetReview() *Review {
	if m != nil {
		return m.Review
	}
	return nil
}

type DeleteReviewResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteReviewResponse) Reset()         { *m = DeleteReviewResponse{} }
func (m *DeleteReviewResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteReviewResponse) ProtoMessage()    {}
func (*DeleteReviewResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{22}
}

func (m *DeleteReviewResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteReviewResponse.Unmarshal(m, b)
}
func (m *DeleteReviewResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteReviewResponse.Marshal(b, m, deterministic)
}
func (m *DeleteReviewResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteReviewResponse.Merge(m, src)
}
func (m *DeleteReviewResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteReviewResponse.Size(m)
}
func (m *DeleteReviewResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteReviewResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteReviewResponse proto.InternalMessageInfo

type UpdateReviewRequest struct {
	Review               *Review  `protobuf:"bytes,1,opt,name=review,proto3" json:"review,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateReviewRequest) Reset()         { *m = UpdateReviewRequest{} }
func (m *UpdateReviewRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateReviewRequest) ProtoMessage()    {}
func (*UpdateReviewRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{23}
}

func (m *UpdateReviewRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateReviewRequest.Unmarshal(m, b)
}
func (m *UpdateReviewRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateReviewRequest.Marshal(b, m, deterministic)
}
func (m *UpdateReviewRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateReviewRequest.Merge(m, src)
}
func (m *UpdateReviewRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateReviewRequest.Size(m)
}
func (m *UpdateReviewRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateReviewRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateReviewRequest proto.InternalMessageInfo

func (m *UpdateReviewRequest) GetReview() *Review {
	if m != nil {
		return m.Review
	}
	return nil
}

type UpdateReviewResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateReviewResponse) Reset()         { *m = UpdateReviewResponse{} }
func (m *UpdateReviewResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateReviewResponse) ProtoMessage()    {}
func (*UpdateReviewResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{24}
}

func (m *UpdateReviewResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateReviewResponse.Unmarshal(m, b)
}
func (m *UpdateReviewResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateReviewResponse.Marshal(b, m, deterministic)
}
func (m *UpdateReviewResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateReviewResponse.Merge(m, src)
}
func (m *UpdateReviewResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateReviewResponse.Size(m)
}
func (m *UpdateReviewResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateReviewResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateReviewResponse proto.InternalMessageInfo

type ListReviewsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListReviewsRequest) Reset()         { *m = ListReviewsRequest{} }
func (m *ListReviewsRequest) String() string { return proto.CompactTextString(m) }
func (*ListReviewsRequest) ProtoMessage()    {}
func (*ListReviewsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{25}
}

func (m *ListReviewsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListReviewsRequest.Unmarshal(m, b)
}
func (m *ListReviewsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListReviewsRequest.Marshal(b, m, deterministic)
}
func (m *ListReviewsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListReviewsRequest.Merge(m, src)
}
func (m *ListReviewsRequest) XXX_Size() int {
	return xxx_messageInfo_ListReviewsRequest.Size(m)
}
func (m *ListReviewsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListReviewsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListReviewsRequest proto.InternalMessageInfo

type ListReviewsResponse struct {
	Reviews              []*Review `protobuf:"bytes,1,rep,name=reviews,proto3" json:"reviews,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListReviewsResponse) Reset()         { *m = ListReviewsResponse{} }
func (m *ListReviewsResponse) String() string { return proto.CompactTextString(m) }
func (*ListReviewsResponse) ProtoMessage()    {}
func (*ListReviewsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{26}
}

func (m *ListReviewsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListReviewsResponse.Unmarshal(m, b)
}
func (m *ListReviewsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListReviewsResponse.Marshal(b, m, deterministic)
}
func (m *ListReviewsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListReviewsResponse.Merge(m, src)
}
func (m *ListReviewsResponse) XXX_Size() int {
	return xxx_messageInfo_ListReviewsResponse.Size(m)
}
func (m *ListReviewsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListReviewsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListReviewsResponse proto.InternalMessageInfo

func (m *ListReviewsResponse) GetReviews() []*Review {
	if m != nil {
		return m.Reviews
	}
	return nil
}

type DeleteReviewLikeRequest struct {
	Like                 *ReviewLike `protobuf:"bytes,1,opt,name=like,proto3" json:"like,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *DeleteReviewLikeRequest) Reset()         { *m = DeleteReviewLikeRequest{} }
func (m *DeleteReviewLikeRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteReviewLikeRequest) ProtoMessage()    {}
func (*DeleteReviewLikeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{27}
}

func (m *DeleteReviewLikeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteReviewLikeRequest.Unmarshal(m, b)
}
func (m *DeleteReviewLikeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteReviewLikeRequest.Marshal(b, m, deterministic)
}
func (m *DeleteReviewLikeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteReviewLikeRequest.Merge(m, src)
}
func (m *DeleteReviewLikeRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteReviewLikeRequest.Size(m)
}
func (m *DeleteReviewLikeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteReviewLikeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteReviewLikeRequest proto.InternalMessageInfo

func (m *DeleteReviewLikeRequest) GetLike() *ReviewLike {
	if m != nil {
		return m.Like
	}
	return nil
}

type DeleteReviewLikeResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteReviewLikeResponse) Reset()         { *m = DeleteReviewLikeResponse{} }
func (m *DeleteReviewLikeResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteReviewLikeResponse) ProtoMessage()    {}
func (*DeleteReviewLikeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{28}
}

func (m *DeleteReviewLikeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteReviewLikeResponse.Unmarshal(m, b)
}
func (m *DeleteReviewLikeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteReviewLikeResponse.Marshal(b, m, deterministic)
}
func (m *DeleteReviewLikeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteReviewLikeResponse.Merge(m, src)
}
func (m *DeleteReviewLikeResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteReviewLikeResponse.Size(m)
}
func (m *DeleteReviewLikeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteReviewLikeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteReviewLikeResponse proto.InternalMessageInfo

type GetProductRequest struct {
	Product              *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductRequest) Reset()         { *m = GetProductRequest{} }
func (m *GetProductRequest) String() string { return proto.CompactTextString(m) }
func (*GetProductRequest) ProtoMessage()    {}
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{29}
}

func (m *GetProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductRequest.Unmarshal(m, b)
}
func (m *GetProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductRequest.Marshal(b, m, deterministic)
}
func (m *GetProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductRequest.Merge(m, src)
}
func (m *GetProductRequest) XXX_Size() int {
	return xxx_messageInfo_GetProductRequest.Size(m)
}
func (m *GetProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductRequest proto.InternalMessageInfo

func (m *GetProductRequest) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type GetProductResponse struct {
	Product              *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductResponse) Reset()         { *m = GetProductResponse{} }
func (m *GetProductResponse) String() string { return proto.CompactTextString(m) }
func (*GetProductResponse) ProtoMessage()    {}
func (*GetProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{30}
}

func (m *GetProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductResponse.Unmarshal(m, b)
}
func (m *GetProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductResponse.Marshal(b, m, deterministic)
}
func (m *GetProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductResponse.Merge(m, src)
}
func (m *GetProductResponse) XXX_Size() int {
	return xxx_messageInfo_GetProductResponse.Size(m)
}
func (m *GetProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductResponse proto.InternalMessageInfo

func (m *GetProductResponse) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type CreateProductRequest struct {
	Product              *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProductRequest) Reset()         { *m = CreateProductRequest{} }
func (m *CreateProductRequest) String() string { return proto.CompactTextString(m) }
func (*CreateProductRequest) ProtoMessage()    {}
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{31}
}

func (m *CreateProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProductRequest.Unmarshal(m, b)
}
func (m *CreateProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProductRequest.Marshal(b, m, deterministic)
}
func (m *CreateProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProductRequest.Merge(m, src)
}
func (m *CreateProductRequest) XXX_Size() int {
	return xxx_messageInfo_CreateProductRequest.Size(m)
}
func (m *CreateProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProductRequest proto.InternalMessageInfo

func (m *CreateProductRequest) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type CreateProductResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProductResponse) Reset()         { *m = CreateProductResponse{} }
func (m *CreateProductResponse) String() string { return proto.CompactTextString(m) }
func (*CreateProductResponse) ProtoMessage()    {}
func (*CreateProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{32}
}

func (m *CreateProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProductResponse.Unmarshal(m, b)
}
func (m *CreateProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProductResponse.Marshal(b, m, deterministic)
}
func (m *CreateProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProductResponse.Merge(m, src)
}
func (m *CreateProductResponse) XXX_Size() int {
	return xxx_messageInfo_CreateProductResponse.Size(m)
}
func (m *CreateProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProductResponse proto.InternalMessageInfo

type UpdateProductRequest struct {
	Product              *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateProductRequest) Reset()         { *m = UpdateProductRequest{} }
func (m *UpdateProductRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateProductRequest) ProtoMessage()    {}
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{33}
}

func (m *UpdateProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProductRequest.Unmarshal(m, b)
}
func (m *UpdateProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProductRequest.Marshal(b, m, deterministic)
}
func (m *UpdateProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProductRequest.Merge(m, src)
}
func (m *UpdateProductRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateProductRequest.Size(m)
}
func (m *UpdateProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProductRequest proto.InternalMessageInfo

func (m *UpdateProductRequest) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type UpdateProductResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateProductResponse) Reset()         { *m = UpdateProductResponse{} }
func (m *UpdateProductResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateProductResponse) ProtoMessage()    {}
func (*UpdateProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{34}
}

func (m *UpdateProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProductResponse.Unmarshal(m, b)
}
func (m *UpdateProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProductResponse.Marshal(b, m, deterministic)
}
func (m *UpdateProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProductResponse.Merge(m, src)
}
func (m *UpdateProductResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateProductResponse.Size(m)
}
func (m *UpdateProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProductResponse proto.InternalMessageInfo

type DeleteProductRequest struct {
	Product              *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteProductRequest) Reset()         { *m = DeleteProductRequest{} }
func (m *DeleteProductRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteProductRequest) ProtoMessage()    {}
func (*DeleteProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{35}
}

func (m *DeleteProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteProductRequest.Unmarshal(m, b)
}
func (m *DeleteProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteProductRequest.Marshal(b, m, deterministic)
}
func (m *DeleteProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteProductRequest.Merge(m, src)
}
func (m *DeleteProductRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteProductRequest.Size(m)
}
func (m *DeleteProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteProductRequest proto.InternalMessageInfo

func (m *DeleteProductRequest) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type DeleteProductResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteProductResponse) Reset()         { *m = DeleteProductResponse{} }
func (m *DeleteProductResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteProductResponse) ProtoMessage()    {}
func (*DeleteProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{36}
}

func (m *DeleteProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteProductResponse.Unmarshal(m, b)
}
func (m *DeleteProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteProductResponse.Marshal(b, m, deterministic)
}
func (m *DeleteProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteProductResponse.Merge(m, src)
}
func (m *DeleteProductResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteProductResponse.Size(m)
}
func (m *DeleteProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteProductResponse proto.InternalMessageInfo

type ListProductsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListProductsRequest) Reset()         { *m = ListProductsRequest{} }
func (m *ListProductsRequest) String() string { return proto.CompactTextString(m) }
func (*ListProductsRequest) ProtoMessage()    {}
func (*ListProductsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{37}
}

func (m *ListProductsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProductsRequest.Unmarshal(m, b)
}
func (m *ListProductsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProductsRequest.Marshal(b, m, deterministic)
}
func (m *ListProductsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProductsRequest.Merge(m, src)
}
func (m *ListProductsRequest) XXX_Size() int {
	return xxx_messageInfo_ListProductsRequest.Size(m)
}
func (m *ListProductsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProductsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListProductsRequest proto.InternalMessageInfo

type ListProductsResponse struct {
	Products             []*Product `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListProductsResponse) Reset()         { *m = ListProductsResponse{} }
func (m *ListProductsResponse) String() string { return proto.CompactTextString(m) }
func (*ListProductsResponse) ProtoMessage()    {}
func (*ListProductsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{38}
}

func (m *ListProductsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProductsResponse.Unmarshal(m, b)
}
func (m *ListProductsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProductsResponse.Marshal(b, m, deterministic)
}
func (m *ListProductsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProductsResponse.Merge(m, src)
}
func (m *ListProductsResponse) XXX_Size() int {
	return xxx_messageInfo_ListProductsResponse.Size(m)
}
func (m *ListProductsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProductsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListProductsResponse proto.InternalMessageInfo

func (m *ListProductsResponse) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

type SearchRequest struct {
	Query                string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{39}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

type SearchResponse struct {
	Users                []*User    `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Reviews              []*Review  `protobuf:"bytes,2,rep,name=reviews,proto3" json:"reviews,omitempty"`
	Products             []*Product `protobuf:"bytes,3,rep,name=products,proto3" json:"products,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SearchResponse) Reset()         { *m = SearchResponse{} }
func (m *SearchResponse) String() string { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()    {}
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{40}
}

func (m *SearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponse.Unmarshal(m, b)
}
func (m *SearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponse.Marshal(b, m, deterministic)
}
func (m *SearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponse.Merge(m, src)
}
func (m *SearchResponse) XXX_Size() int {
	return xxx_messageInfo_SearchResponse.Size(m)
}
func (m *SearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponse proto.InternalMessageInfo

func (m *SearchResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *SearchResponse) GetReviews() []*Review {
	if m != nil {
		return m.Reviews
	}
	return nil
}

func (m *SearchResponse) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

func init() {
	proto.RegisterEnum("protos.ProductImage_ProductImageType", ProductImage_ProductImageType_name, ProductImage_ProductImageType_value)
	proto.RegisterEnum("protos.ProductLink_ProductLinkType", ProductLink_ProductLinkType_name, ProductLink_ProductLinkType_value)
	proto.RegisterType((*User)(nil), "protos.User")
	proto.RegisterType((*ReviewLike)(nil), "protos.ReviewLike")
	proto.RegisterType((*Review)(nil), "protos.Review")
	proto.RegisterType((*ProductImage)(nil), "protos.ProductImage")
	proto.RegisterType((*ProductLink)(nil), "protos.ProductLink")
	proto.RegisterType((*Product)(nil), "protos.Product")
	proto.RegisterType((*Timestamps)(nil), "protos.Timestamps")
	proto.RegisterType((*GetUserRequest)(nil), "protos.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "protos.GetUserResponse")
	proto.RegisterType((*CreateUserRequest)(nil), "protos.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "protos.CreateUserResponse")
	proto.RegisterType((*UpdateUserRequest)(nil), "protos.UpdateUserRequest")
	proto.RegisterType((*UpdateUserResponse)(nil), "protos.UpdateUserResponse")
	proto.RegisterType((*DeleteUserRequest)(nil), "protos.DeleteUserRequest")
	proto.RegisterType((*DeleteUserResponse)(nil), "protos.DeleteUserResponse")
	proto.RegisterType((*ListUsersRequest)(nil), "protos.ListUsersRequest")
	proto.RegisterType((*ListUsersResponse)(nil), "protos.ListUsersResponse")
	proto.RegisterType((*GetReviewRequest)(nil), "protos.GetReviewRequest")
	proto.RegisterType((*GetReviewResponse)(nil), "protos.GetReviewResponse")
	proto.RegisterType((*CreateReviewRequest)(nil), "protos.CreateReviewRequest")
	proto.RegisterType((*CreateReviewResponse)(nil), "protos.CreateReviewResponse")
	proto.RegisterType((*DeleteReviewRequest)(nil), "protos.DeleteReviewRequest")
	proto.RegisterType((*DeleteReviewResponse)(nil), "protos.DeleteReviewResponse")
	proto.RegisterType((*UpdateReviewRequest)(nil), "protos.UpdateReviewRequest")
	proto.RegisterType((*UpdateReviewResponse)(nil), "protos.UpdateReviewResponse")
	proto.RegisterType((*ListReviewsRequest)(nil), "protos.ListReviewsRequest")
	proto.RegisterType((*ListReviewsResponse)(nil), "protos.ListReviewsResponse")
	proto.RegisterType((*DeleteReviewLikeRequest)(nil), "protos.DeleteReviewLikeRequest")
	proto.RegisterType((*DeleteReviewLikeResponse)(nil), "protos.DeleteReviewLikeResponse")
	proto.RegisterType((*GetProductRequest)(nil), "protos.GetProductRequest")
	proto.RegisterType((*GetProductResponse)(nil), "protos.GetProductResponse")
	proto.RegisterType((*CreateProductRequest)(nil), "protos.CreateProductRequest")
	proto.RegisterType((*CreateProductResponse)(nil), "protos.CreateProductResponse")
	proto.RegisterType((*UpdateProductRequest)(nil), "protos.UpdateProductRequest")
	proto.RegisterType((*UpdateProductResponse)(nil), "protos.UpdateProductResponse")
	proto.RegisterType((*DeleteProductRequest)(nil), "protos.DeleteProductRequest")
	proto.RegisterType((*DeleteProductResponse)(nil), "protos.DeleteProductResponse")
	proto.RegisterType((*ListProductsRequest)(nil), "protos.ListProductsRequest")
	proto.RegisterType((*ListProductsResponse)(nil), "protos.ListProductsResponse")
	proto.RegisterType((*SearchRequest)(nil), "protos.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "protos.SearchResponse")
}

func init() { proto.RegisterFile("protos.proto", fileDescriptor_5da3cbeb884d181c) }

var fileDescriptor_5da3cbeb884d181c = []byte{
	// 1099 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x58, 0x5f, 0x4f, 0x1b, 0x47,
	0x10, 0xf7, 0xf9, 0x6f, 0x19, 0x3b, 0xc6, 0x0c, 0x06, 0x8e, 0x4b, 0xd3, 0x58, 0x5b, 0xa5, 0x22,
	0x6a, 0x45, 0xaa, 0x4b, 0xab, 0x28, 0x6d, 0xd3, 0x88, 0x10, 0x44, 0x29, 0xd4, 0x41, 0x17, 0x50,
	0xd4, 0x97, 0x22, 0xc7, 0xde, 0xd0, 0x13, 0xc6, 0x76, 0xee, 0xce, 0x69, 0xf9, 0x0c, 0x7d, 0xee,
	0x4b, 0x5f, 0xfa, 0xc9, 0x9a, 0xb7, 0x7e, 0x8f, 0xe8, 0xf6, 0xcf, 0xed, 0xee, 0xdd, 0x99, 0x80,
	0x93, 0xa7, 0xdc, 0xee, 0xcc, 0xfc, 0x66, 0x76, 0x66, 0xfc, 0xfb, 0x45, 0x40, 0x63, 0x12, 0x8c,
	0xa3, 0x71, 0xb8, 0xc9, 0xfe, 0xc1, 0x2a, 0x3f, 0x39, 0xb7, 0x4f, 0xc7, 0xe3, 0xd3, 0x21, 0xbd,
	0xc7, 0x8e, 0x2f, 0xa7, 0xaf, 0xee, 0x45, 0xfe, 0x39, 0x0d, 0xa3, 0xde, 0xf9, 0x84, 0x3b, 0x92,
	0xdf, 0xa0, 0x7c, 0x1c, 0xd2, 0x00, 0x9b, 0x50, 0xf4, 0x07, 0xb6, 0xd5, 0xb1, 0x36, 0x16, 0xbc,
	0xa2, 0x3f, 0x40, 0x17, 0x20, 0x71, 0x0d, 0xed, 0x62, 0xc7, 0xda, 0xa8, 0xbb, 0xb8, 0x29, 0x72,
	0x1c, 0x25, 0x16, 0x4f, 0xf3, 0x42, 0x84, 0xf2, 0xa8, 0x77, 0x4e, 0xed, 0x12, 0x43, 0x61, 0xdf,
	0xe4, 0x15, 0x80, 0x47, 0xdf, 0xf8, 0xf4, 0x8f, 0x03, 0xff, 0x8c, 0x66, 0xb2, 0x7c, 0x01, 0xd5,
	0x80, 0x59, 0x45, 0x86, 0xa6, 0xcc, 0xc0, 0x63, 0x3c, 0x61, 0xc5, 0x0e, 0x94, 0xa7, 0x21, 0x0d,
	0x18, 0x72, 0xdd, 0x6d, 0x48, 0xaf, 0xb8, 0x72, 0x8f, 0x59, 0xc8, 0x7f, 0x16, 0x54, 0x79, 0xd0,
	0x47, 0x79, 0xca, 0x5d, 0xa8, 0x4d, 0x82, 0xf1, 0x60, 0xda, 0x8f, 0x44, 0xce, 0x45, 0x19, 0x70,
	0xc8, 0xaf, 0x3d, 0x69, 0x4f, 0x6a, 0x2b, 0xcf, 0xaa, 0x0d, 0x6d, 0xa8, 0xf5, 0xc7, 0xa3, 0x88,
	0x8e, 0x22, 0xbb, 0xc2, 0xaa, 0x92, 0x47, 0xdc, 0x80, 0xca, 0xd0, 0x3f, 0xa3, 0xa1, 0x5d, 0xed,
	0x94, 0xf4, 0xaa, 0x54, 0xcb, 0x3c, 0xee, 0x40, 0xfe, 0xb5, 0xa0, 0x21, 0x52, 0xef, 0x9d, 0xf7,
	0x4e, 0xb3, 0xad, 0x7c, 0x08, 0xe5, 0xe8, 0x62, 0x42, 0xd9, 0xfb, 0x9a, 0xee, 0x9d, 0x54, 0xb9,
	0x2c, 0xc6, 0x38, 0x1c, 0x5d, 0x4c, 0xa8, 0xc7, 0x42, 0xb0, 0x05, 0xa5, 0x69, 0x30, 0x14, 0x63,
	0x8b, 0x3f, 0x89, 0x0b, 0xad, 0xb4, 0x2f, 0x7e, 0x06, 0xce, 0xa1, 0xf7, 0xec, 0xe9, 0xf1, 0xf6,
	0xd1, 0xc9, 0xde, 0x2f, 0x5b, 0xbb, 0x3b, 0x27, 0x47, 0xbf, 0x1e, 0xee, 0x9c, 0x1c, 0x77, 0xf7,
	0xbb, 0xcf, 0x5e, 0x74, 0x5b, 0x05, 0xf2, 0x8f, 0x05, 0x75, 0x11, 0x74, 0xe0, 0x8f, 0xce, 0x32,
	0x05, 0x3e, 0x30, 0x0a, 0xfc, 0x3c, 0x55, 0x60, 0x1c, 0xa2, 0x7f, 0x5f, 0x5a, 0xde, 0xd7, 0xb0,
	0x98, 0x72, 0xc5, 0x5b, 0xb0, 0x2e, 0xab, 0x3b, 0xd8, 0xeb, 0xee, 0xa7, 0x8b, 0x7b, 0x6b, 0x41,
	0x4d, 0x84, 0x7c, 0x94, 0xfd, 0x68, 0x43, 0x25, 0xf2, 0xa3, 0xa1, 0xdc, 0x75, 0x7e, 0xc0, 0x0e,
	0xd4, 0x07, 0x34, 0xec, 0x07, 0xfe, 0x24, 0xf2, 0xc7, 0x23, 0xb6, 0x11, 0x0b, 0x9e, 0x7e, 0x85,
	0x5f, 0x41, 0xd5, 0x8f, 0x3b, 0x1a, 0xda, 0x15, 0x36, 0xf1, 0x76, 0xde, 0x9c, 0x3c, 0xe1, 0x83,
	0x77, 0xe3, 0xf5, 0x18, 0x9d, 0xc9, 0xf5, 0x58, 0xce, 0xe9, 0x99, 0xc7, 0x3d, 0xc8, 0x9f, 0x00,
	0xaa, 0x54, 0xfc, 0x06, 0x6a, 0xfd, 0x80, 0xf6, 0x22, 0x3a, 0x10, 0x6b, 0xe9, 0x6c, 0x72, 0x22,
	0xd8, 0x94, 0x44, 0xa0, 0x1e, 0xe6, 0x49, 0xd7, 0x38, 0x6a, 0x3a, 0x19, 0xb0, 0xa8, 0xca, 0xfb,
	0xa3, 0x84, 0x2b, 0x71, 0xa1, 0xb9, 0x4b, 0x23, 0xb6, 0xee, 0xf4, 0xf5, 0x94, 0x86, 0xea, 0x17,
	0x61, 0xcd, 0xfc, 0xb5, 0xde, 0x87, 0xc5, 0x24, 0x26, 0x9c, 0x8c, 0x47, 0x21, 0xbd, 0x42, 0xd0,
	0xb7, 0xb0, 0xb4, 0xcd, 0x2a, 0xbd, 0x5e, 0xae, 0x36, 0xa0, 0x1e, 0xc6, 0xd3, 0xc5, 0x60, 0xc7,
	0xec, 0x01, 0xd7, 0x06, 0xd3, 0xc3, 0x14, 0xd8, 0x53, 0x3a, 0xa4, 0x73, 0x80, 0xe9, 0x61, 0x02,
	0x0c, 0xa1, 0x75, 0xe0, 0x87, 0xac, 0x39, 0xa1, 0xc0, 0x22, 0x0f, 0x60, 0x49, 0xbb, 0x13, 0x1d,
	0x23, 0x50, 0x89, 0x61, 0x42, 0xdb, 0x62, 0xdb, 0x61, 0x66, 0xe0, 0x26, 0xf2, 0x1d, 0xb4, 0x76,
	0x69, 0x24, 0xd8, 0x54, 0x14, 0xa6, 0x48, 0xd7, 0xba, 0x8c, 0x74, 0xc9, 0xf7, 0xb0, 0xa4, 0xc5,
	0x8a, 0xa4, 0x57, 0x0d, 0x7e, 0x04, 0xcb, 0xbc, 0xeb, 0xf3, 0xe5, 0x5e, 0x85, 0xb6, 0x19, 0x2e,
	0x9a, 0xf3, 0x08, 0x96, 0x79, 0xcb, 0xe6, 0x86, 0x35, 0xc3, 0x15, 0x2c, 0x1f, 0xeb, 0xdc, 0xb0,
	0x66, 0xb8, 0x80, 0x6d, 0x03, 0xc6, 0x63, 0xe3, 0xb7, 0xc9, 0x30, 0x1f, 0xc3, 0xb2, 0x71, 0x2b,
	0x3a, 0xbb, 0x01, 0x35, 0x0e, 0x27, 0x07, 0x9a, 0xce, 0x26, 0xcd, 0x64, 0x0b, 0xd6, 0xf4, 0x57,
	0x30, 0x99, 0x48, 0x2a, 0x2e, 0xc7, 0x7a, 0x21, 0xea, 0xcd, 0xd3, 0x13, 0x66, 0x27, 0x0e, 0xd8,
	0x59, 0x08, 0x51, 0xf5, 0x8f, 0x6c, 0xee, 0x52, 0xe7, 0x04, 0xb0, 0x26, 0x88, 0xd6, 0xe5, 0x82,
	0x48, 0x1e, 0x03, 0xea, 0xf1, 0xe2, 0x79, 0xd7, 0x00, 0xd8, 0x92, 0xc3, 0x9f, 0xbf, 0x86, 0x35,
	0x58, 0x49, 0x41, 0x88, 0xc7, 0x6d, 0xc9, 0x51, 0x7d, 0x10, 0x76, 0x0a, 0x42, 0x61, 0xf3, 0xa6,
	0x7e, 0x10, 0x76, 0x0a, 0x42, 0x60, 0xaf, 0xf0, 0xa5, 0x11, 0xd7, 0xc9, 0x2e, 0x6d, 0x43, 0xdb,
	0xbc, 0x16, 0xdd, 0xfe, 0x12, 0x3e, 0x11, 0x90, 0x72, 0x9b, 0x32, 0x39, 0x13, 0x07, 0x72, 0x07,
	0x6e, 0x3c, 0xa7, 0xbd, 0xa0, 0xff, 0xbb, 0x2c, 0xb8, 0x0d, 0x95, 0xd7, 0x53, 0x1a, 0x5c, 0x08,
	0x91, 0xe4, 0x07, 0xf2, 0x97, 0x05, 0x4d, 0xe9, 0x77, 0x75, 0x0a, 0xd2, 0xf7, 0xba, 0x78, 0xe9,
	0x5e, 0x1b, 0x45, 0x97, 0xde, 0x53, 0xb4, 0xfb, 0x7f, 0x11, 0x1a, 0x8c, 0x0f, 0x9f, 0xd3, 0xe0,
	0x8d, 0xdf, 0xa7, 0xf8, 0x03, 0xd4, 0x84, 0xa6, 0xe0, 0xaa, 0x0c, 0x33, 0x85, 0xc9, 0x59, 0xcb,
	0xdc, 0x8b, 0xee, 0x16, 0x70, 0x07, 0x40, 0xa9, 0x04, 0xae, 0x4b, 0xc7, 0x8c, 0xe0, 0x38, 0x4e,
	0x9e, 0x49, 0x87, 0x51, 0xfa, 0xa0, 0x60, 0x32, 0x52, 0xa3, 0x60, 0x72, 0xe4, 0x84, 0xc1, 0x28,
	0x65, 0x50, 0x30, 0x19, 0x91, 0x51, 0x30, 0x39, 0x42, 0x52, 0xc0, 0x27, 0xb0, 0x90, 0xc8, 0x06,
	0xda, 0xd2, 0x35, 0xad, 0x2e, 0xce, 0x7a, 0x8e, 0x45, 0x62, 0xb8, 0x6f, 0x4b, 0xd0, 0x14, 0x54,
	0x25, 0x3b, 0xfd, 0x04, 0x16, 0x12, 0x61, 0x50, 0xb0, 0x69, 0x9d, 0x51, 0xb0, 0x19, 0x15, 0x21,
	0x05, 0xdc, 0x87, 0x86, 0x4e, 0xf0, 0x78, 0xd3, 0x6c, 0xab, 0x89, 0xf4, 0x69, 0xbe, 0x51, 0x07,
	0xd3, 0xf9, 0x57, 0x81, 0xe5, 0x90, 0xba, 0x02, 0xcb, 0xa5, 0x6c, 0x06, 0xa6, 0x53, 0xa3, 0x02,
	0xcb, 0x11, 0x1e, 0x05, 0x96, 0x2b, 0x2b, 0x05, 0xfc, 0x09, 0xea, 0x1a, 0xd7, 0xa3, 0xa3, 0x77,
	0xda, 0x94, 0x05, 0xe7, 0x66, 0xae, 0x2d, 0x41, 0x7a, 0x01, 0xad, 0x34, 0x63, 0xe3, 0xed, 0xbc,
	0xec, 0x9a, 0x1c, 0x38, 0x9d, 0xd9, 0x0e, 0xc9, 0x80, 0xff, 0x2e, 0x25, 0xff, 0x9b, 0x4e, 0x26,
	0xbc, 0x03, 0xa0, 0x28, 0x1c, 0xf5, 0x41, 0x9a, 0xd4, 0xa6, 0xf6, 0x2f, 0xcb, 0xf8, 0xa4, 0x80,
	0x5d, 0xb8, 0x61, 0xb0, 0x30, 0xa6, 0x06, 0x99, 0x02, 0xbb, 0x35, 0xc3, 0xaa, 0xe3, 0x19, 0xcc,
	0x8b, 0xa9, 0x59, 0xce, 0xc2, 0xcb, 0xa7, 0x6b, 0x86, 0x67, 0xb0, 0x2d, 0xa6, 0xc6, 0x39, 0x0b,
	0x2f, 0x9f, 0xa2, 0xd9, 0xea, 0xe8, 0x6c, 0x8c, 0xc6, 0x48, 0x53, 0xd4, 0xad, 0x56, 0x27, 0x8f,
	0xc0, 0x49, 0xc1, 0xfd, 0x59, 0xb2, 0xb2, 0x1c, 0xca, 0x43, 0xa8, 0xf2, 0x0b, 0x5c, 0x91, 0xa1,
	0x06, 0x6d, 0x3b, 0xab, 0xe9, 0x6b, 0x89, 0xf5, 0x92, 0xff, 0x39, 0xe0, 0xfe, 0xbb, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xd1, 0x85, 0xf2, 0x28, 0x25, 0x10, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UsersServiceClient is the client API for UsersService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UsersServiceClient interface {
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error)
	ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error)
}

type usersServiceClient struct {
	cc *grpc.ClientConn
}

func NewUsersServiceClient(cc *grpc.ClientConn) UsersServiceClient {
	return &usersServiceClient{cc}
}

func (c *usersServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, "/protos.UsersService/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/protos.UsersService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error) {
	out := new(UpdateUserResponse)
	err := c.cc.Invoke(ctx, "/protos.UsersService/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error) {
	out := new(DeleteUserResponse)
	err := c.cc.Invoke(ctx, "/protos.UsersService/DeleteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error) {
	out := new(ListUsersResponse)
	err := c.cc.Invoke(ctx, "/protos.UsersService/ListUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsersServiceServer is the server API for UsersService service.
type UsersServiceServer interface {
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)
	DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error)
	ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error)
}

func RegisterUsersServiceServer(s *grpc.Server, srv UsersServiceServer) {
	s.RegisterService(&_UsersService_serviceDesc, srv)
}

func _UsersService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.UsersService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.UsersService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.UsersService/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.UsersService/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.UsersService/ListUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).ListUsers(ctx, req.(*ListUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UsersService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.UsersService",
	HandlerType: (*UsersServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _UsersService_GetUser_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _UsersService_CreateUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _UsersService_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _UsersService_DeleteUser_Handler,
		},
		{
			MethodName: "ListUsers",
			Handler:    _UsersService_ListUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos.proto",
}

// ReviewsServiceClient is the client API for ReviewsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReviewsServiceClient interface {
	GetReview(ctx context.Context, in *GetReviewRequest, opts ...grpc.CallOption) (*GetReviewResponse, error)
	CreateReview(ctx context.Context, in *CreateReviewRequest, opts ...grpc.CallOption) (*CreateReviewResponse, error)
	UpdateReview(ctx context.Context, in *UpdateReviewRequest, opts ...grpc.CallOption) (*UpdateReviewResponse, error)
	DeleteReview(ctx context.Context, in *DeleteReviewRequest, opts ...grpc.CallOption) (*DeleteReviewResponse, error)
	ListReviews(ctx context.Context, in *ListReviewsRequest, opts ...grpc.CallOption) (*ListReviewsResponse, error)
	// todo decide if to add AddReviewLike endpoint
	DeleteReviewLike(ctx context.Context, in *DeleteReviewLikeRequest, opts ...grpc.CallOption) (*DeleteReviewLikeResponse, error)
}

type reviewsServiceClient struct {
	cc *grpc.ClientConn
}

func NewReviewsServiceClient(cc *grpc.ClientConn) ReviewsServiceClient {
	return &reviewsServiceClient{cc}
}

func (c *reviewsServiceClient) GetReview(ctx context.Context, in *GetReviewRequest, opts ...grpc.CallOption) (*GetReviewResponse, error) {
	out := new(GetReviewResponse)
	err := c.cc.Invoke(ctx, "/protos.ReviewsService/GetReview", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewsServiceClient) CreateReview(ctx context.Context, in *CreateReviewRequest, opts ...grpc.CallOption) (*CreateReviewResponse, error) {
	out := new(CreateReviewResponse)
	err := c.cc.Invoke(ctx, "/protos.ReviewsService/CreateReview", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewsServiceClient) UpdateReview(ctx context.Context, in *UpdateReviewRequest, opts ...grpc.CallOption) (*UpdateReviewResponse, error) {
	out := new(UpdateReviewResponse)
	err := c.cc.Invoke(ctx, "/protos.ReviewsService/UpdateReview", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewsServiceClient) DeleteReview(ctx context.Context, in *DeleteReviewRequest, opts ...grpc.CallOption) (*DeleteReviewResponse, error) {
	out := new(DeleteReviewResponse)
	err := c.cc.Invoke(ctx, "/protos.ReviewsService/DeleteReview", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewsServiceClient) ListReviews(ctx context.Context, in *ListReviewsRequest, opts ...grpc.CallOption) (*ListReviewsResponse, error) {
	out := new(ListReviewsResponse)
	err := c.cc.Invoke(ctx, "/protos.ReviewsService/ListReviews", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewsServiceClient) DeleteReviewLike(ctx context.Context, in *DeleteReviewLikeRequest, opts ...grpc.CallOption) (*DeleteReviewLikeResponse, error) {
	out := new(DeleteReviewLikeResponse)
	err := c.cc.Invoke(ctx, "/protos.ReviewsService/DeleteReviewLike", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReviewsServiceServer is the server API for ReviewsService service.
type ReviewsServiceServer interface {
	GetReview(context.Context, *GetReviewRequest) (*GetReviewResponse, error)
	CreateReview(context.Context, *CreateReviewRequest) (*CreateReviewResponse, error)
	UpdateReview(context.Context, *UpdateReviewRequest) (*UpdateReviewResponse, error)
	DeleteReview(context.Context, *DeleteReviewRequest) (*DeleteReviewResponse, error)
	ListReviews(context.Context, *ListReviewsRequest) (*ListReviewsResponse, error)
	// todo decide if to add AddReviewLike endpoint
	DeleteReviewLike(context.Context, *DeleteReviewLikeRequest) (*DeleteReviewLikeResponse, error)
}

func RegisterReviewsServiceServer(s *grpc.Server, srv ReviewsServiceServer) {
	s.RegisterService(&_ReviewsService_serviceDesc, srv)
}

func _ReviewsService_GetReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewsServiceServer).GetReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.ReviewsService/GetReview",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewsServiceServer).GetReview(ctx, req.(*GetReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReviewsService_CreateReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewsServiceServer).CreateReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.ReviewsService/CreateReview",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewsServiceServer).CreateReview(ctx, req.(*CreateReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReviewsService_UpdateReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewsServiceServer).UpdateReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.ReviewsService/UpdateReview",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewsServiceServer).UpdateReview(ctx, req.(*UpdateReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReviewsService_DeleteReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewsServiceServer).DeleteReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.ReviewsService/DeleteReview",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewsServiceServer).DeleteReview(ctx, req.(*DeleteReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReviewsService_ListReviews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReviewsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewsServiceServer).ListReviews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.ReviewsService/ListReviews",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewsServiceServer).ListReviews(ctx, req.(*ListReviewsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReviewsService_DeleteReviewLike_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteReviewLikeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewsServiceServer).DeleteReviewLike(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.ReviewsService/DeleteReviewLike",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewsServiceServer).DeleteReviewLike(ctx, req.(*DeleteReviewLikeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ReviewsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.ReviewsService",
	HandlerType: (*ReviewsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetReview",
			Handler:    _ReviewsService_GetReview_Handler,
		},
		{
			MethodName: "CreateReview",
			Handler:    _ReviewsService_CreateReview_Handler,
		},
		{
			MethodName: "UpdateReview",
			Handler:    _ReviewsService_UpdateReview_Handler,
		},
		{
			MethodName: "DeleteReview",
			Handler:    _ReviewsService_DeleteReview_Handler,
		},
		{
			MethodName: "ListReviews",
			Handler:    _ReviewsService_ListReviews_Handler,
		},
		{
			MethodName: "DeleteReviewLike",
			Handler:    _ReviewsService_DeleteReviewLike_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos.proto",
}

// ProductsServiceClient is the client API for ProductsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProductsServiceClient interface {
	GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*GetProductResponse, error)
	CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*CreateProductResponse, error)
	UpdateProduct(ctx context.Context, in *UpdateProductRequest, opts ...grpc.CallOption) (*UpdateProductResponse, error)
	DeleteProduct(ctx context.Context, in *DeleteProductRequest, opts ...grpc.CallOption) (*DeleteProductResponse, error)
	ListProducts(ctx context.Context, in *ListProductsRequest, opts ...grpc.CallOption) (*ListProductsResponse, error)
}

type productsServiceClient struct {
	cc *grpc.ClientConn
}

func NewProductsServiceClient(cc *grpc.ClientConn) ProductsServiceClient {
	return &productsServiceClient{cc}
}

func (c *productsServiceClient) GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*GetProductResponse, error) {
	out := new(GetProductResponse)
	err := c.cc.Invoke(ctx, "/protos.ProductsService/GetProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsServiceClient) CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*CreateProductResponse, error) {
	out := new(CreateProductResponse)
	err := c.cc.Invoke(ctx, "/protos.ProductsService/CreateProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsServiceClient) UpdateProduct(ctx context.Context, in *UpdateProductRequest, opts ...grpc.CallOption) (*UpdateProductResponse, error) {
	out := new(UpdateProductResponse)
	err := c.cc.Invoke(ctx, "/protos.ProductsService/UpdateProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsServiceClient) DeleteProduct(ctx context.Context, in *DeleteProductRequest, opts ...grpc.CallOption) (*DeleteProductResponse, error) {
	out := new(DeleteProductResponse)
	err := c.cc.Invoke(ctx, "/protos.ProductsService/DeleteProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsServiceClient) ListProducts(ctx context.Context, in *ListProductsRequest, opts ...grpc.CallOption) (*ListProductsResponse, error) {
	out := new(ListProductsResponse)
	err := c.cc.Invoke(ctx, "/protos.ProductsService/ListProducts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductsServiceServer is the server API for ProductsService service.
type ProductsServiceServer interface {
	GetProduct(context.Context, *GetProductRequest) (*GetProductResponse, error)
	CreateProduct(context.Context, *CreateProductRequest) (*CreateProductResponse, error)
	UpdateProduct(context.Context, *UpdateProductRequest) (*UpdateProductResponse, error)
	DeleteProduct(context.Context, *DeleteProductRequest) (*DeleteProductResponse, error)
	ListProducts(context.Context, *ListProductsRequest) (*ListProductsResponse, error)
}

func RegisterProductsServiceServer(s *grpc.Server, srv ProductsServiceServer) {
	s.RegisterService(&_ProductsService_serviceDesc, srv)
}

func _ProductsService_GetProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServiceServer).GetProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.ProductsService/GetProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServiceServer).GetProduct(ctx, req.(*GetProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductsService_CreateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServiceServer).CreateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.ProductsService/CreateProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServiceServer).CreateProduct(ctx, req.(*CreateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductsService_UpdateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServiceServer).UpdateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.ProductsService/UpdateProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServiceServer).UpdateProduct(ctx, req.(*UpdateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductsService_DeleteProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServiceServer).DeleteProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.ProductsService/DeleteProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServiceServer).DeleteProduct(ctx, req.(*DeleteProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductsService_ListProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServiceServer).ListProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.ProductsService/ListProducts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServiceServer).ListProducts(ctx, req.(*ListProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProductsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.ProductsService",
	HandlerType: (*ProductsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProduct",
			Handler:    _ProductsService_GetProduct_Handler,
		},
		{
			MethodName: "CreateProduct",
			Handler:    _ProductsService_CreateProduct_Handler,
		},
		{
			MethodName: "UpdateProduct",
			Handler:    _ProductsService_UpdateProduct_Handler,
		},
		{
			MethodName: "DeleteProduct",
			Handler:    _ProductsService_DeleteProduct_Handler,
		},
		{
			MethodName: "ListProducts",
			Handler:    _ProductsService_ListProducts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos.proto",
}

// SearchServiceClient is the client API for SearchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SearchServiceClient interface {
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
}

type searchServiceClient struct {
	cc *grpc.ClientConn
}

func NewSearchServiceClient(cc *grpc.ClientConn) SearchServiceClient {
	return &searchServiceClient{cc}
}

func (c *searchServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, "/protos.SearchService/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchServiceServer is the server API for SearchService service.
type SearchServiceServer interface {
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
}

func RegisterSearchServiceServer(s *grpc.Server, srv SearchServiceServer) {
	s.RegisterService(&_SearchService_serviceDesc, srv)
}

func _SearchService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.SearchService/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SearchService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.SearchService",
	HandlerType: (*SearchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _SearchService_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos.proto",
}
