/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.protos.Review');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.protos.Product');
goog.require('proto.protos.ReviewLike');
goog.require('proto.protos.Timestamps');
goog.require('proto.protos.User');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.protos.Review = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.protos.Review.repeatedFields_, null);
};
goog.inherits(proto.protos.Review, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.protos.Review.displayName = 'proto.protos.Review';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.protos.Review.repeatedFields_ = [6];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.protos.Review.prototype.toObject = function(opt_includeInstance) {
  return proto.protos.Review.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.protos.Review} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.protos.Review.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    timestamps: (f = msg.getTimestamps()) && proto.protos.Timestamps.toObject(includeInstance, f),
    product: (f = msg.getProduct()) && proto.protos.Product.toObject(includeInstance, f),
    user: (f = msg.getUser()) && proto.protos.User.toObject(includeInstance, f),
    content: jspb.Message.getFieldWithDefault(msg, 5, ""),
    likesList: jspb.Message.toObjectList(msg.getLikesList(),
    proto.protos.ReviewLike.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.protos.Review}
 */
proto.protos.Review.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.protos.Review;
  return proto.protos.Review.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.protos.Review} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.protos.Review}
 */
proto.protos.Review.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = new proto.protos.Timestamps;
      reader.readMessage(value,proto.protos.Timestamps.deserializeBinaryFromReader);
      msg.setTimestamps(value);
      break;
    case 3:
      var value = new proto.protos.Product;
      reader.readMessage(value,proto.protos.Product.deserializeBinaryFromReader);
      msg.setProduct(value);
      break;
    case 4:
      var value = new proto.protos.User;
      reader.readMessage(value,proto.protos.User.deserializeBinaryFromReader);
      msg.setUser(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setContent(value);
      break;
    case 6:
      var value = new proto.protos.ReviewLike;
      reader.readMessage(value,proto.protos.ReviewLike.deserializeBinaryFromReader);
      msg.addLikes(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.protos.Review.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.protos.Review.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.protos.Review} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.protos.Review.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTimestamps();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.protos.Timestamps.serializeBinaryToWriter
    );
  }
  f = message.getProduct();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.protos.Product.serializeBinaryToWriter
    );
  }
  f = message.getUser();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.protos.User.serializeBinaryToWriter
    );
  }
  f = message.getContent();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getLikesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      proto.protos.ReviewLike.serializeBinaryToWriter
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.protos.Review.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.protos.Review.prototype.setId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional Timestamps timestamps = 2;
 * @return {?proto.protos.Timestamps}
 */
proto.protos.Review.prototype.getTimestamps = function() {
  return /** @type{?proto.protos.Timestamps} */ (
    jspb.Message.getWrapperField(this, proto.protos.Timestamps, 2));
};


/** @param {?proto.protos.Timestamps|undefined} value */
proto.protos.Review.prototype.setTimestamps = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.protos.Review.prototype.clearTimestamps = function() {
  this.setTimestamps(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.protos.Review.prototype.hasTimestamps = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional Product product = 3;
 * @return {?proto.protos.Product}
 */
proto.protos.Review.prototype.getProduct = function() {
  return /** @type{?proto.protos.Product} */ (
    jspb.Message.getWrapperField(this, proto.protos.Product, 3));
};


/** @param {?proto.protos.Product|undefined} value */
proto.protos.Review.prototype.setProduct = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.protos.Review.prototype.clearProduct = function() {
  this.setProduct(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.protos.Review.prototype.hasProduct = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional User user = 4;
 * @return {?proto.protos.User}
 */
proto.protos.Review.prototype.getUser = function() {
  return /** @type{?proto.protos.User} */ (
    jspb.Message.getWrapperField(this, proto.protos.User, 4));
};


/** @param {?proto.protos.User|undefined} value */
proto.protos.Review.prototype.setUser = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.protos.Review.prototype.clearUser = function() {
  this.setUser(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.protos.Review.prototype.hasUser = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional string content = 5;
 * @return {string}
 */
proto.protos.Review.prototype.getContent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.protos.Review.prototype.setContent = function(value) {
  jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * repeated ReviewLike likes = 6;
 * @return {!Array<!proto.protos.ReviewLike>}
 */
proto.protos.Review.prototype.getLikesList = function() {
  return /** @type{!Array<!proto.protos.ReviewLike>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.protos.ReviewLike, 6));
};


/** @param {!Array<!proto.protos.ReviewLike>} value */
proto.protos.Review.prototype.setLikesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.protos.ReviewLike=} opt_value
 * @param {number=} opt_index
 * @return {!proto.protos.ReviewLike}
 */
proto.protos.Review.prototype.addLikes = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.protos.ReviewLike, opt_index);
};


proto.protos.Review.prototype.clearLikesList = function() {
  this.setLikesList([]);
};


